# Generated by Django 4.1.7 on 2023-05-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
