# Generated by Django 4.1.7 on 2023-05-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_record_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='reg_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
